#!/bin/sh
#-
# Copyright (c) 2015 HardenedBSD
# Author: Shawn Webb <shawn.webb@hardenedbsd.org>
#
# This work originally sponsored by G2, Inc
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
# 1. Redistributions of source code must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
# 2. Redistributions in binary form must reproduce the above copyright
#    notice, this list of conditions and the following disclaimer in the
#    documentation and/or other materials provided with the distribution.
#
# THIS SOFTWARE IS PROVIDED BY THE AUTHOR AND CONTRIBUTORS ``AS IS'' AND
# ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED.  IN NO EVENT SHALL THE AUTHOR OR CONTRIBUTORS BE LIABLE
# FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
# OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
# HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
# LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
# OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
# SUCH DAMAGE.

tmpdir=""
buildver=""
zfsbe=""
mountpoint="/"
dnsrec="$(uname -m).$(uname -r).updates.hardenedbsd.org"
capath="/usr/share/keys/hbsd-update/trusted"
branch="hardened_current_master"
baseurl=""
kernel="HARDENEDBSD"
unsigned=0
verbose=0

debug_print() {
	echo -e "${1}" >&2
}

usage() {
	debug_print "USAGE: ${0} OPTIONS"
	debug_print "OPTIONS:"
	debug_print "\t-b BEname\tInstall updates to ZFS Boot Environment <BEname>"
	debug_print "\t-B branch\tBranch to use with the base URL"
	debug_print "\t-c CApath\tPath (file or directory) to the CA cert(s)"
	debug_print "\t-d dnsrec\tDNS record name to use for checking version info"
	debug_print "\t-h\t\tShow this help screen"
	debug_print "\t-j jailname\tInstall updates to jail <jailname>"
	debug_print "\t-k kernel\tUse different kernel (default: HARDENEDBSD)"
	debug_print "\t-t tmpdir\tTemporary directory"
	debug_print "\t-u url\t\tFetch update from a different URL"
	debug_print "\t-U\t\tAllow unsigned updates"
	debug_print "\t-v version\tUse a different version"
	debug_print "\t-V\t\tVerbose output"
	exit 1
}

get_baseurl() {
	if [ ! -z "${baseurl}" ]; then
		echo ${baseurl}
		return 0
	fi

	baseurl="http://updates.hardenedbsd.org/pub/updates/${branch}/$(uname -r)/$(uname -m)"

	echo ${baseurl}

	return 0
}

get_tmpdir() {
	if [ -z "${tmpdir}" ]; then
		tmpdir=$(mktemp -d)
	fi

	echo ${tmpdir}

	return 0
}

get_version() {
	if [ ! -z "${buildver}" ]; then
		echo ${buildver}
		return 0
	fi

	res=$(host -t txt ${dnsrec} | \
		awk '{print $4;}' | \
		sed 's,",,g')

	buildver=$(echo ${res} | sed 's,|, ,g' | awk '{print $2;}')
	if [ -z "${buildver}" ]; then
		return 1
	fi

	echo ${buildver}

	if [ ${verbose} -gt 0 ]; then
		debug_print "[*] Latest build: ${buildver}"
	fi

	return 0
}

fetch_update() {
	fetch -o ${tmpdir}/update.tar \
		${baseurl}/update-$(get_version).tar
	res=${?}
	if [ ${res} -gt 0 ]; then
		return ${res}
	fi

	tar -xf ${tmpdir}/update.tar \
		-C ${tmpdir}
	res=${?}
	if [ ${res} -gt 0 ]; then
		return ${res}
	fi

	return 0
}

check_pubkey_validity() {
	if [ ${verbose} -gt 0 ]; then
		debug_print "[*] Checking validity of the public key"
	fi

	caopt="-CApath"
	if [ -f ${capath} ]; then
		caopt="-CAfile"
	fi

	openssl verify \
		${caopt} ${capath} \
		${tmpdir}/pubkey.pem \
		> /dev/null 2>&1
	return ${res}
}

check_set_validity() {
	checkfiles="base.txz kernel-${kernel}.txz skip.txt"

	openssl x509 \
		-in ${tmpdir}/pubkey.pem \
		-pubkey \
		-noout \
		> ${tmpdir}/pubkey.rsa.pem
	res=${?}
	if [ ${res} -gt 0 ]; then
		debug_print "[-] Could not extract public key"
		return 1
	fi

	for file in $(echo ${checkfiles}); do
		if [ ${verbose} -gt 0 ]; then
			debug_print "[*] Checking the validity of ${file}"
		fi

		signedhash=$(openssl rsautl \
			-verify \
			-in ${tmpdir}/${file}.sig \
			-pubin \
			-inkey ${tmpdir}/pubkey.rsa.pem)

		computedhash=$(sha512 -q ${tmpdir}/${file})
		if [ ! "${signedhash}" = "${computedhash}" ]; then
			debug_print "[-] Hashes don't match for ${file}. Signed: ${signedhash}. Computed ${computedhash}."
			return 1
		fi
	done

	return 0
}

apply_base() {
	if [ ${verbose} -gt 0 ]; then
		debug_print "[*] Applying base"
	fi

	chflags -R noschg \
		/bin \
		/sbin \
		/lib \
		/libexec \
		/usr/bin \
		/usr/sbin \
		/usr/lib
	res=${?}
	if [ ${res} -gt 0 ]; then
		return ${res}
	fi

	tar -xpf ${tmpdir}/base.txz \
		-X ${tmpdir}/skip.txt \
		-C ${mountpoint}
}

apply_kernel() {
	if [ ${verbose} -gt 0 ]; then
		debug_print "[*] Applying kernel ${kernel}"
	fi

	tar -xpf ${tmpdir}/kernel-${kernel}.txz \
		-X ${tmpdir}/skip.txt \
		-C ${mountpoint}
	kldxref /boot/kernel
	return ${?}
}

create_be() {
	if [ -z "${zfsbe}" ]; then
		return 0
	fi

	beadm create ${zfsbe}
	res=${?}
	if [ ${res} -gt 0 ]; then
		return ${res}
	fi

	mountpoint=$(mktemp -d)
	beadm mount ${zfsbe} ${mountpoint}
	res=${?}
	if [ ${res} -gt 0 ]; then
		return ${res}
	fi

	return 0
}

activate_be() {
	if [ -z "${zfsbe}" ]; then
		return 0
	fi

	beadm umount ${zfsbe}
	res=${?}
	if [ ${res} -gt 0 ]; then
		return ${res}
	fi

	beadm activate ${zfsbe}
	res=${?}
	if [ ${res} -gt 0 ]; then
		return ${res}
	fi

	return 0
}

cleanup() {
	rm -rf ${tmpdir}
}

main() {
	while getopts 'hUVb:B:d:j:k:t:u:v:' opt; do
		case "${opt}" in
			b)
				if ! which -s beadm; then
					debug_print "[*] Please install the beadm pkg."
					exit 1
				fi

				zfsbe="${OPTARG}"
				exit 1
				;;
			B)
				branch="${OPTARG}"
				;;
			c)
				capath="${OPTARG}"
				;;
			d)
				dnsrec="${OPTARG}"
				;;
			j)
				debug_print "Installing to a jail is not supported, yet."
				exit 1
				;;
			k)
				kernel="${OPTARG}"
				;;
			t)
				tmpdir="${OPTARG}"
				;;
			u)
				baseurl="${OPTARG}"
				;;
			U)
				unsigned=1
				;;
			v)
				buildver="${OPTARG}"
				;;
			V)
				verbose=1
				;;
			*)
				usage
				;;
		esac
	done

	if [ -z "${tmpdir}" ]; then
		get_tmpdir > /dev/null
	fi

	if [ -z "${buildver}" ]; then
		get_version > /dev/null
		res=${?}
		if [ ${res} -gt 0 ]; then
			debug_print "[*] Could not get the version number"
			cleanup
			exit 1
		fi
	fi
	get_baseurl > /dev/null
	res=${?}
	if [ ${res} -gt 0 ]; then
		debug_print "[*] Could not get the version number"
		cleanup
		exit 1
	fi

	fetch_update
	res=${?}
	if [ ${res} -gt 0 ]; then
		cleanup
		exit 1
	fi

	if [ ${unsigned} -eq 0 ]; then
		check_pubkey_validity
		res=${?}
		if [ ${res} -gt 0 ]; then
			cleanup
			debug_print "[*] Public key failed to validate."
			exit 1
		fi

		check_set_validity
		res=${?}
		if [ ${res} -gt 0 ]; then
			cleanup
			debug_print "[*] Public key failed to validate."
			exit 1
		fi
	fi

	create_be
	res=${?}
	if [ ${res} -gt 0 ]; then
		cleanup
		exit 1
	fi

	apply_base
	res=${?}
	if [ ${res} -gt 0 ]; then
		cleanup
		exit 1
	fi

	apply_kernel
	res=${?}
	if [ ${res} -gt 0 ]; then
		cleanup
		exit 1
	fi

	activate_be
	res=${?}
	if [ ${res} -gt 0 ]; then
		cleanup
		exit 1
	fi

	cleanup
	exit 0
}

main "${@}"
